# Copyright (c) E5R Development Team. All rights reserved.
# Licensed under the Apache License, Version 2.0. More license information in LICENSE.txt.

image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 1

environment:
  CODECOV_UPLOAD_TOKEN:
    secure: GOUHfNAquS/rtP4gxA131uc6WZhGoHIsp66q7ECbzuvRJCNwKSfsFQRPeu2M6k6l

artifacts:
  - path: 'artifacts\E5R.Architecture.*.nupkg'
    name: E5RArchitecturePackages

init:
  - ps: 'git config --global core.autocrlf true'

install:
  - ps: '$ENV:BUILD_LABEL = "alpha-ci"'
  - ps: '$ENV:BUILD_VERSION_SUFFIX = "${ENV:BUILD_LABEL}-${ENV:APPVEYOR_BUILD_NUMBER}"'
  - ps: '$ENV:BUILD_VERSION = (Select-Xml -Path ".\packages.props" -XPath "/Project/PropertyGroup/VersionPrefix" | Select-Object -ExpandProperty Node).InnerText'
  - ps: 'Update-AppveyorBuild -Version "${ENV:BUILD_VERSION}-${ENV:BUILD_VERSION_SUFFIX}"'
  - ps: 'choco install opencover.portable'
  - ps: 'choco install codecov'

before_build:
  - ps: 'dotnet --info'
  - ps: 'choco --version'

build_script:
  - ps: 'dotnet build .\E5R.Architecture.Packages.sln -c ${ENV:CONFIGURATION} --version-suffix ${ENV:BUILD_VERSION_SUFFIX}'
  - ps: 'dotnet pack .\E5R.Architecture.Packages.sln --no-build -c ${ENV:CONFIGURATION} --version-suffix ${ENV:BUILD_VERSION_SUFFIX}'

test_script :
  - ps: 'opencover.console -register:user -target:"dotnet.exe" -targetargs:"test .\test\E5R.Architecture.Core.Test" -output:".\E5R.Architecture.Core.Test.Coverage.xml" -oldstyle'

after_test:
  - ps: 'codecov -f .\E5R.Architecture.Core.Test.Coverage.xml -t ${ENV:CODECOV_UPLOAD_TOKEN}'

deploy:
  - provider: NuGet
    api_key:
      secure: L2C2Jcwls+oHt30Vh3pw72SitjtPKB9qsYjiI2FYhhC831yb6I9j3OSpHoOccWpu
    skip_symbols: true
    artifact: E5RArchitecturePackages

  - provider: GitHub
    tag: v0.1.0-alpha     # todo: Usar versão dinâmica
    release: 0.1.0-alpha  # todo: Usar versão dinâmica
    description: 'CI Release v$(appveyor_build_version) from AppVeyor' # todo: Usar versão dinâmica
    artifact: E5RArchitecturePackages
    draft: true
    prerelease: true
    force_update: true
    on:
      branch: master
    auth_token:
      secure: RsQffcoeH/0NhhYdhhcRBs/XuVwJq5KPYcfX19XmkNCrolsPiMWpJcabHLq62+4j
