# Copyright (c) E5R Development Team. All rights reserved.
# Licensed under the Apache License, Version 2.0. More license information in LICENSE.txt.

version: '0.1.0-alpha-ci-{build}'
image: Visual Studio 2017

platform: x64
configuration: Release
clone_depth: 1

artifacts:
  - path: 'dist\E5R.Architecture.*.nupkg'
    name: E5RArchitecturePackages

init:
  - ps: 'git config --global core.autocrlf true'

before_build:
  - ps: 'dotnet --info'

build_script:
  - ps: 'dotnet build .\E5R.Architecture.Packages.sln -c ${ENV:CONFIGURATION} --version-suffix alpha-ci-${ENV:APPVEYOR_BUILD_NUMBER}'
  - ps: 'dotnet pack .\E5R.Architecture.Packages.sln --no-build -c ${ENV:CONFIGURATION} --version-suffix alpha-ci-${ENV:APPVEYOR_BUILD_NUMBER}'

test_script :
  - ps: 'dotnet test .\test\E5R.Architecture.Core.Test'

deploy:
  - provider: NuGet
    api_key:
      secure: L2C2Jcwls+oHt30Vh3pw72SitjtPKB9qsYjiI2FYhhC831yb6I9j3OSpHoOccWpu
    skip_symbols: true
    artifact: E5RArchitecturePackages

  - provider: GitHub
    tag: v0.1.0-alpha
    release: 0.1.0-alpha
    description: 'CI Release v$(appveyor_build_version) from AppVeyor'
    artifact: E5RArchitecturePackages
    draft: true
    prerelease: true
    force_update: true
    on:
      branch: master
    auth_token:
      secure: RsQffcoeH/0NhhYdhhcRBs/XuVwJq5KPYcfX19XmkNCrolsPiMWpJcabHLq62+4j
