# Copyright (c) E5R Development Team. All rights reserved.
# Licensed under the Apache License, Version 2.0. More license information in LICENSE.txt.

image: Visual Studio 2019
configuration: Release
platform: Any CPU
clone_depth: 1
skip_tags: true

branches:
  only:
    - master
    - develop

artifacts:
  - path: 'artifacts\E5R.Architecture.*.nupkg'
    name: E5RArchitecturePackages

init:
  - ps: 'git config --global core.autocrlf true'
  - ps: 'dotnet tool install --global Codecov.Tool'

before_build:
  - ps: 'dotnet --info'
  - ps: 'dotnet restore'

build_script:
  - ps: >-
      if ($ENV:BUILD_VERSION_SUFFIX) {
        dotnet build .\E5R.Architecture.sln --no-restore -c ${ENV:CONFIGURATION} --version-suffix ${ENV:BUILD_VERSION_SUFFIX};
      } else {
        dotnet build .\E5R.Architecture.sln --no-restore -c ${ENV:CONFIGURATION};
      }

test_script:
  - ps: 'dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover'
  # - ps: >-
  #     if (("develop", "master").contains(${ENV:APPVEYOR_REPO_BRANCH})) {
  #       codecov -f .\test\E5R.Architecture.Core.Test\TestResults\coverage.opencover.xml';
  #       codecov -f .\test\E5R.Architecture.Data.Test\TestResults\coverage.opencover.xml';
  #       codecov -f .\test\E5R.Architecture.Data.Dapper.Test\TestResults\coverage.opencover.xml';
  #       codecov -f .\test\E5R.Architecture.Data.EntityFrameworkCore.Test\TestResults\coverage.opencover.xml';
  #       codecov -f .\test\E5R.Architecture.Business.Test\TestResults\coverage.opencover.xml';
  #       codecov -f .\test\E5R.Architecture.Infrastructure.Test\TestResults\coverage.opencover.xml';
  #     }

for:
-
  branches:
    only:
      - master
  install:
    - ps: >-
        $BUILD_VERSION = (Select-Xml -Path ".\packages.props" -XPath "/Project/PropertyGroup/VersionPrefix" | Select-Object -ExpandProperty Node).InnerText;
        Update-AppveyorBuild -Version "${BUILD_VERSION}";
  deploy:
    - provider: GitHub
      tag: v$(appveyor_build_version)
      release: $(appveyor_build_version)
      description: 'CI Release v$(appveyor_build_version) from AppVeyor'
      artifact: E5RArchitecturePackages
      auth_token:
        secure: ZEaPbdCkQoEXD/52qVLt7n6Kl6uCV/d/ba644DCMt86YRJs8kvpaprkYK6I5wUdq
    - provider: NuGet
      api_key:
        secure: UiEhClEPf4VHjZt2bs/qkDFuwOxfhWn7dOC0yywa+7IXrJU2oX2f619taoR345Gp
      skip_symbols: true
      artifact: E5RArchitecturePackages

-
  branches:
    only:
      - develop
  install:
    - ps: >-
        $BUILD_TIMESTAMP = (Get-Date -Format "yyyyMMddHHmmss");
        $BUILD_LABEL = "beta";
        $BUILD_NUMBER = "{0:00000}" -f [int]::parse("${ENV:APPVEYOR_BUILD_NUMBER}");
        $ENV:BUILD_VERSION_SUFFIX = "${BUILD_LABEL}-${BUILD_TIMESTAMP}-${BUILD_NUMBER}";
        $BUILD_VERSION = (Select-Xml -Path ".\packages.props" -XPath "/Project/PropertyGroup/VersionPrefix" | Select-Object -ExpandProperty Node).InnerText;
        Update-AppveyorBuild -Version "${BUILD_VERSION}-${ENV:BUILD_VERSION_SUFFIX}";
  deploy:
    - provider: GitHub
      tag: v$(appveyor_build_version)
      release: $(appveyor_build_version)
      description: 'CI Release v$(appveyor_build_version) from AppVeyor'
      artifact: E5RArchitecturePackages
      prerelease: true
      auth_token:
        secure: ZEaPbdCkQoEXD/52qVLt7n6Kl6uCV/d/ba644DCMt86YRJs8kvpaprkYK6I5wUdq
    - provider: NuGet
      api_key:
        secure: UiEhClEPf4VHjZt2bs/qkDFuwOxfhWn7dOC0yywa+7IXrJU2oX2f619taoR345Gp
      skip_symbols: true
      artifact: E5RArchitecturePackages
