# Copyright (c) E5R Development Team. All rights reserved.
# Licensed under the Apache License, Version 2.0. More license information in LICENSE.txt.

image: Visual Studio 2019
configuration: Release
platform: Any CPU

clone_depth: 1

branches:
  only:
    - master
    - develop

skip_tags: true

artifacts:
  - path: 'artifacts\E5R.Architecture.*.nupkg'
    name: E5RArchitecturePackages

init:
  - ps: 'git config --global core.autocrlf true'

install:
  - ps: >-
      $BUILD_LABEL = "beta";
      $BUILD_NUMBER = "{0:00000}" -f [int]::parse("${ENV:APPVEYOR_BUILD_NUMBER}");
      $ENV:BUILD_VERSION_SUFFIX = "-${BUILD_LABEL}.${BUILD_NUMBER}";
    on:
      branch: develop
  - ps: >-
      $ENV:BUILD_VERSION_SUFFIX = "";
    on:
      branch: master
  - ps: >-
      $BUILD_VERSION = (Select-Xml -Path ".\packages.props" -XPath "/Project/PropertyGroup/VersionPrefix" | Select-Object -ExpandProperty Node).InnerText;
      Update-AppveyorBuild -Version "${BUILD_VERSION}${ENV:BUILD_VERSION_SUFFIX}";

before_build:
  - ps: 'dotnet --info'

build_script:
  - ps: 'dotnet build .\E5R.Architecture.sln -c ${ENV:CONFIGURATION} --version-suffix ${ENV:BUILD_VERSION_SUFFIX}'

test_script :
  - ps: 'dotnet test .\test\E5R.Architecture.Core.Test'
  - ps: 'dotnet test .\test\E5R.Architecture.Data.Test'
  - ps: 'dotnet test .\test\E5R.Architecture.Data.Dapper.Test'
  - ps: 'dotnet test .\test\E5R.Architecture.Data.EntityFrameworkCore.Test'
  - ps: 'dotnet test .\test\E5R.Architecture.Business.Test'
  - ps: 'dotnet test .\test\E5R.Architecture.Infrastructure.Test'

deploy:
  - provider: NuGet
    api_key:
      secure: UiEhClEPf4VHjZt2bs/qkDFuwOxfhWn7dOC0yywa+7IXrJU2oX2f619taoR345Gp
    skip_symbols: true
    on:
      branch:
        - master
        - develop
    artifact: E5RArchitecturePackages

  - provider: GitHub
    tag: $(appveyor_build_version)
    release: $(appveyor_build_version)
    description: 'CI Release v$(appveyor_build_version) from AppVeyor'
    artifact: E5RArchitecturePackages
    on:
      branch: master
    auth_token:
      secure: ZEaPbdCkQoEXD/52qVLt7n6Kl6uCV/d/ba644DCMt86YRJs8kvpaprkYK6I5wUdq

  - provider: GitHub
    tag: $(appveyor_build_version)
    release: $(appveyor_build_version)
    description: 'CI Release v$(appveyor_build_version) from AppVeyor'
    artifact: E5RArchitecturePackages
    prerelease: true
    on:
      branch: develop
    auth_token:
      secure: ZEaPbdCkQoEXD/52qVLt7n6Kl6uCV/d/ba644DCMt86YRJs8kvpaprkYK6I5wUdq
    
