# Copyright (c) E5R Development Team. All rights reserved.
# Licensed under the Apache License, Version 2.0. More license information in LICENSE.txt.

image: Visual Studio 2019
configuration: Release
platform: Any CPU
clone_depth: 1
skip_tags: true

environment:
  BUILD_LABEL: beta

branches:
  only:
    - master
    - develop

artifacts:
  - path: 'artifacts\E5R.Architecture.*.$(appveyor_build_version).nupkg'
    name: E5RArchitecturePackages

init:
  - ps: 'git config --global core.autocrlf true'
  - ps: 'dotnet tool install --global Codecov.Tool'
  - ps: 'if(-not $ENV:APPVEYOR_PULL_REQUEST_NUMBER) { $ENV:IS_NOT_PR = "true"; }'
  - ps: 'write-host "init.IS_NOT_PR: ${ENV:IS_NOT_PR}"'

before_build:
  - ps: 'dotnet --info'
  - ps: 'dotnet restore'

build_script:
  - ps: >-
      if ($ENV:BUILD_VERSION_SUFFIX) {
        dotnet build .\E5R.Architecture.sln --no-restore -c ${ENV:CONFIGURATION} --version-suffix ${ENV:BUILD_VERSION_SUFFIX};
      } else {
        dotnet build .\E5R.Architecture.sln --no-restore -c ${ENV:CONFIGURATION};
      }

test_script:
  - ps: 'dotnet test --collect:"XPlat Code Coverage"'
  - ps: 'codecov -Z -F unittests'

for:
-
  branches:
    only:
      - master
  install:
    - ps: >-
        write-host "install.IS_NOT_PR: ${ENV:IS_NOT_PR}";
        if(-not $ENV:APPVEYOR_PULL_REQUEST_NUMBER) {
          $BUILD_VERSION = (Select-Xml -Path ".\packages.props" -XPath "/Project/PropertyGroup/VersionPrefix" | Select-Object -ExpandProperty Node).InnerText;
          Update-AppveyorBuild -Version "${BUILD_VERSION}";
        } else {
          $BUILD_NUMBER = "{0:000}" -f [int]::parse("${ENV:APPVEYOR_BUILD_NUMBER}");
          $ENV:BUILD_VERSION_SUFFIX = "${ENV:BUILD_LABEL}-${BUILD_NUMBER}";
          $BUILD_VERSION = (Select-Xml -Path ".\packages.props" -XPath "/Project/PropertyGroup/VersionPrefix" | Select-Object -ExpandProperty Node).InnerText;
          Update-AppveyorBuild -Version "${BUILD_VERSION}-${ENV:BUILD_VERSION_SUFFIX}";
        }
  deploy:
    - provider: GitHub
      tag: v$(appveyor_build_version)
      APPVEYOR_PULL_REQUEST_NUMBER: false
      release: $(appveyor_build_version)
      description: 'CI Release v$(appveyor_build_version) from AppVeyor'
      artifact: E5RArchitecturePackages
      auth_token:
        secure: ZEaPbdCkQoEXD/52qVLt7n6Kl6uCV/d/ba644DCMt86YRJs8kvpaprkYK6I5wUdq
      on:
        IS_NOT_PR: true
    - provider: NuGet
      api_key:
        secure: UiEhClEPf4VHjZt2bs/qkDFuwOxfhWn7dOC0yywa+7IXrJU2oX2f619taoR345Gp
      skip_symbols: true
      artifact: E5RArchitecturePackages
      on:
        IS_NOT_PR: true

-
  branches:
    only:
      - develop
  install:
    - ps: >-
        write-host "install.IS_NOT_PR: ${ENV:IS_NOT_PR}";
        $BUILD_NUMBER = "{0:000}" -f [int]::parse("${ENV:APPVEYOR_BUILD_NUMBER}");
        $ENV:BUILD_VERSION_SUFFIX = "${ENV:BUILD_LABEL}-${BUILD_NUMBER}";
        $BUILD_VERSION = (Select-Xml -Path ".\packages.props" -XPath "/Project/PropertyGroup/VersionPrefix" | Select-Object -ExpandProperty Node).InnerText;
        Update-AppveyorBuild -Version "${BUILD_VERSION}-${ENV:BUILD_VERSION_SUFFIX}";
  deploy:
    - provider: GitHub
      tag: v$(appveyor_build_version)
      release: $(appveyor_build_version)
      description: 'CI Release v$(appveyor_build_version) from AppVeyor'
      artifact: E5RArchitecturePackages
      prerelease: true
      auth_token:
        secure: ZEaPbdCkQoEXD/52qVLt7n6Kl6uCV/d/ba644DCMt86YRJs8kvpaprkYK6I5wUdq
      on:
        IS_NOT_PR: true
    - provider: NuGet
      api_key:
        secure: UiEhClEPf4VHjZt2bs/qkDFuwOxfhWn7dOC0yywa+7IXrJU2oX2f619taoR345Gp
      skip_symbols: true
      artifact: E5RArchitecturePackages
      on:
        IS_NOT_PR: true
