# Copyright (c) E5R Development Team. All rights reserved.
# Licensed under the Apache License, Version 2.0. More license information in LICENSE.txt.

image: Visual Studio 2017
configuration: Release
platform: Any CPU

clone_depth: 1

environment:
  CODECOV_TOKEN:
    secure: GOUHfNAquS/rtP4gxA131uc6WZhGoHIsp66q7ECbzuvRJCNwKSfsFQRPeu2M6k6l

artifacts:
  - path: 'artifacts\E5R.Architecture.*.nupkg'
    name: E5RArchitecturePackages

cache:
  - '%ProgramData%\chocolatey\bin -> appveyor.yml'
  - '%ProgramData%\chocolatey\lib -> appveyor.yml'

init:
  - ps: 'git config --global core.autocrlf true'

install:
  - ps: >-
      "APPVEYOR_BUILD_NUMBER = $ENV:APPVEYOR_BUILD_NUMBER" | write-host
      "APPVEYOR_PULL_REQUEST_NUMBER = $ENV:APPVEYOR_PULL_REQUEST_NUMBER" | write-host
      "APPVEYOR_REPO_BRANCH = $ENV:APPVEYOR_REPO_BRANCH" | write-host
      "APPVEYOR_REPO_TAG = $ENV:APPVEYOR_REPO_TAG" | write-host
      "APPVEYOR_REPO_TAG_NAME = $ENV:APPVEYOR_REPO_TAG_NAME" | write-host
      "APPVEYOR_REPO_COMMIT = $ENV:APPVEYOR_REPO_COMMIT" | write-host
      
      $BUILD_LABEL = "alpha";
      $BUILD_NUMBER = "{0:00000}" -f [int]::parse("${ENV:APPVEYOR_BUILD_NUMBER}");
      $ENV:BUILD_VERSION_SUFFIX = "${BUILD_LABEL}-${BUILD_NUMBER}";
      $BUILD_VERSION = (Select-Xml -Path ".\packages.props" -XPath "/Project/PropertyGroup/VersionPrefix" | Select-Object -ExpandProperty Node).InnerText;
      Update-AppveyorBuild -Version "${BUILD_VERSION}-${ENV:BUILD_VERSION_SUFFIX}";
      if(!(test-path ${env:ProgramData}\chocolatey\bin\opencover.console.exe))
      {
        cinst opencover.portable;
      }
      if(!(test-path ${env:ProgramData}\chocolatey\bin\codecov.exe))
      {
        cinst codecov;
      }

before_build:
  - ps: 'dotnet --info'

build_script:
  - ps: 'dotnet build .\E5R.Architecture.Packages.sln -c ${ENV:CONFIGURATION} --version-suffix ${ENV:BUILD_VERSION_SUFFIX}'

test_script :
  - ps: 'opencover.console -register:user -target:"dotnet.exe" -targetargs:"test .\test\E5R.Architecture.Core.Test" -output:".\E5R.Architecture.Core.Test.Coverage.xml" -oldstyle'
  - ps: 'opencover.console -register:user -target:"dotnet.exe" -targetargs:"test .\test\E5R.Architecture.Data.Test" -output:".\E5R.Architecture.Data.Test.Coverage.xml" -oldstyle'

after_test:
  - ps: 'codecov -f .\E5R.Architecture.Core.Test.Coverage.xml --build $ENV:APPVEYOR_BUILD_NUMBER --branch $ENV:APPVEYOR_REPO_BRANCH --sha $ENV:APPVEYOR_REPO_COMMIT'
  - ps: 'codecov -f .\E5R.Architecture.Data.Test.Coverage.xml --build $ENV:APPVEYOR_BUILD_NUMBER --branch $ENV:APPVEYOR_REPO_BRANCH --sha $ENV:APPVEYOR_REPO_COMMIT'

deploy:
  - provider: NuGet
    api_key:
      secure: L2C2Jcwls+oHt30Vh3pw72SitjtPKB9qsYjiI2FYhhC831yb6I9j3OSpHoOccWpu
    skip_symbols: true
    on:
      branch: master
    artifact: E5RArchitecturePackages

  - provider: GitHub
    tag: v0.1.0-alpha     # todo: Usar versão dinâmica
    release: 0.1.0-alpha  # todo: Usar versão dinâmica
    description: 'CI Release v$(appveyor_build_version) from AppVeyor' # todo: Usar versão dinâmica
    artifact: E5RArchitecturePackages
    draft: true
    prerelease: true
    force_update: true
    on:
      branch: master
    auth_token:
      secure: RsQffcoeH/0NhhYdhhcRBs/XuVwJq5KPYcfX19XmkNCrolsPiMWpJcabHLq62+4j
