name: Build and Publish On-Line Documentation

on:
  push:
    branches:
      - develop
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Checkout "doc-live" branch
      uses: actions/checkout@v2
      with:
        ref: doc-live
        path: .doc-live
    - name: Get docfx
      run: |
        curl -L https://github.com/dotnet/docfx/releases/latest/download/docfx.zip -o docfx.zip
        unzip -d .docfx docfx.zip
    - name: Build docs
      run:  mono .docfx/docfx.exe docs/docfx.json
    - name: Clear .doc-live/docs/*
      run: rm -rf .doc-live/docs/*
    - name: Copy docs/_site to .doc-live/docs/
      run: cp -rf docs/_site/* .doc-live/docs/

  publish:
    name: Publish
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Checkout "doc-live" branch
      uses: actions/checkout@v2
      with:
        ref: doc-live
        path: .doc-live
    - name: Get docfx
      run: |
        curl -L https://github.com/dotnet/docfx/releases/latest/download/docfx.zip -o docfx.zip
        unzip -d .docfx docfx.zip
    - name: Build docs
      run:  mono .docfx/docfx.exe docs/docfx.json
    - name: Clear .doc-live/docs/*
      run: rm -rf .doc-live/docs/*
    - name: Copy docs/_site to .doc-live/docs/
      run: cp -rf docs/_site/* .doc-live/docs/
    - name: Commit and push to "doc-live" branch
      run: |
        export GIT_COMMITTER_NAME=$(git show -s --format='%cn')
        export GIT_COMMITTER_EMAIL=$(git show -s --format='%ce')
        export GIT_AUTHOR_NAME=$(git show -s --format='%an')
        export GIT_AUTHOR_EMAIL=$(git show -s --format='%ae')
        export COMMIT_HASH=$(git show -s --format='%H')
        export SUBJECT=$(git show -s --format='%s')
        cd .doc-live
        git add .
        git commit -m "$SUBJECT" -m "Original commit: $COMMIT_HASH"
        git push origin HEAD:doc-live
